var MDN_Persona = [
	"Persona",
	"Persona/.well-known-browserid",
	"Persona/Bootstrapping_Persona",
	"Persona/FAQ",
	"Persona/Glossary",
	"Persona/IdP_Development_Tips",
	"Persona/Identity_Provider_Overview",
	"Persona/Implementing_a_Persona_IdP",
	"Persona/Libraries_and_plugins",
	"Persona/Protocol_Overview",
	"Persona/Quick_Setup",
	"Persona/Remote_Verification_API",
	"Persona/Security_Considerations",
	"Persona/Why_Persona",
	"Persona/Why_Persona_",
	"Persona/ss",
	"Persona/x"
];